name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: dummy
      DB_HOST: localhost
      DB_PORT: "5432"
      DB_NAME: test
      DB_USER: test

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Ruff (Lint)
        run: ruff check .

      - name: Ruff (Format)
        run: ruff format --check .

      - name: MyPy (Types)
        run: mypy .

      - name: Pytest
        run: pytest

  docker-build-check:
    runs-on: ubuntu-latest
    needs: test-and-lint
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Docker check
        run: docker compose -f docker/docker-compose.yml build
